title: my firts repository
description: 'hello everybody, this is my firts repository. nice too meet you.'
template:
  repo: my-firts-repository-template
  name: my-firts-repository
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
